name: Firebase Secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod  # Define environment variable to specify which secrets to use

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "::set-env name=FIREBASE_API_KEY::${{ secrets.FIREBASE_API_KEY }}"
          echo "::set-env name=FIREBASE_AUTH_DOMAIN::${{ secrets.FIREBASE_AUTH_DOMAIN }}"
          echo "::set-env name=FIREBASE_PROJECT_ID::${{ secrets.FIREBASE_PROJECT_ID }}"
          echo "::set-env name=FIREBASE_STORAGE_BUCKET::${{ secrets.FIREBASE_STORAGE_BUCKET }}"
          echo "::set-env name=FIREBASE_MESSAGING_SENDER_ID::${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
          echo "::set-env name=FIREBASE_APP_ID::${{ secrets.FIREBASE_APP_ID }}"
          echo "::set-env name=FIREBASE_MEASUREMENT_ID::${{ secrets.FIREBASE_MEASUREMENT_ID }}"

      - name: Display environment variables
        run: |
          echo "FIREBASE_API_KEY: $FIREBASE_API_KEY"
          echo "FIREBASE_AUTH_DOMAIN: $FIREBASE_AUTH_DOMAIN"
          echo "FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID"
          echo "FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET"
          echo "FIREBASE_MESSAGING_SENDER_ID: $FIREBASE_MESSAGING_SENDER_ID"
          echo "FIREBASE_APP_ID: $FIREBASE_APP_ID"
          echo "FIREBASE_MEASUREMENT_ID: $FIREBASE_MEASUREMENT_ID"

      # Additional steps for deployment process
